package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strings"
)

const propsURL = "https://raw.githubusercontent.com/mdn/data/main/css/properties.json"

func main() {
	resp, err := http.Get(propsURL)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}

	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		log.Fatal(err)
	}

	names := make([]string, 0, len(raw))
	for k := range raw {
		// Skip custom-property-like or malformed entries (e.g. "--*")
		if strings.HasPrefix(k, "--") {
			continue
		}
		names = append(names, k)
	}
	sort.Strings(names)

	f, err := os.Create("style_generated.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by cmd/gencss from mdn/data; DO NOT EDIT.")
	fmt.Fprintln(f, "package htmlbuilder")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// Style holds every known CSS property as a typed string field.")
	fmt.Fprintln(f, "// Zero-value (empty string) fields are skipped when applied via CSS().")
	fmt.Fprintln(f, "type Style struct {")

	seen := make(map[string]bool)
	type fieldEntry struct{ field, cssProp string }
	var fields []fieldEntry

	for _, cssProp := range names {
		field := toPascalCase(cssProp)
		if field == "" || seen[field] {
			continue // skip collisions (rare, e.g. vendor-prefixed dupes)
		}
		seen[field] = true
		fields = append(fields, fieldEntry{field, cssProp})
		fmt.Fprintf(f, "\t%s string\n", field)
	}
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f)

	fmt.Fprintln(f, "var fieldToCSSProp = map[string]string{")
	for _, fe := range fields {
		fmt.Fprintf(f, "\t%q: %q,\n", fe.field, fe.cssProp)
	}
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f)

	// Generate the CSS() method applying every field via reflection-free
	// direct field access, so no reflect package needed at runtime.
	fmt.Fprintln(f, "// CSS applies a Style struct to the node, skipping zero-value fields.")
	fmt.Fprintln(f, "func (n *Node) CSS(s Style) *Node {")
	for _, fe := range fields {
		fmt.Fprintf(f, "\tif s.%s != \"\" {\n\t\tn.setStyle(%q, s.%s)\n\t}\n", fe.field, fe.cssProp, fe.field)
	}
	fmt.Fprintln(f, "\treturn n")
	fmt.Fprintln(f, "}")

	// extras 

	fmt.Fprintln(f, "// styleToAttrs converts a Style struct into its set attrs, skipping zero-value fields.")
	fmt.Fprintln(f, "func styleToAttrs(s Style) []attr {")
	fmt.Fprintln(f, "\tvar out []attr")
	for _, fe := range fields {
		fmt.Fprintf(f, "\tif s.%s != \"\" {\n\t\tout = append(out, attr{%q, s.%s})\n\t}\n", fe.field, fe.cssProp, fe.field)
	}
	fmt.Fprintln(f, "\treturn out")
	fmt.Fprintln(f, "}")

	log.Printf("generated %d CSS properties into style_generated.go\n", len(fields))
}

// toPascalCase converts a kebab-case CSS property name into a Go-style
// PascalCase identifier: "background-color" -> "BackgroundColor",
// "-webkit-appearance" -> "WebkitAppearance".
func toPascalCase(cssProp string) string {
	parts := strings.Split(cssProp, "-")
	var sb strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		sb.WriteString(strings.ToUpper(p[:1]))
		sb.WriteString(p[1:])
	}
	return sb.String()
}
