// Code generated by cmd/gentags; DO NOT EDIT.
package htmlbuilder

func A(text string) *Node                { return El("a").Text(text) }
func Abbr(text string) *Node             { return El("abbr").Text(text) }
func Address(children ...*Node) *Node    { return El("address").Child(children...) }
func Area() *Node                        { return El("area") }
func Article(children ...*Node) *Node    { return El("article").Child(children...) }
func Aside(children ...*Node) *Node      { return El("aside").Child(children...) }
func Audio(children ...*Node) *Node      { return El("audio").Child(children...) }
func B(text string) *Node                { return El("b").Text(text) }
func Base() *Node                        { return El("base") }
func Bdi(text string) *Node              { return El("bdi").Text(text) }
func Bdo(text string) *Node              { return El("bdo").Text(text) }
func Blockquote(children ...*Node) *Node { return El("blockquote").Child(children...) }
func Body(children ...*Node) *Node       { return El("body").Child(children...) }
func Br() *Node                          { return El("br") }
func Button(children ...*Node) *Node     { return El("button").Child(children...) }
func Canvas(children ...*Node) *Node     { return El("canvas").Child(children...) }
func Caption(text string) *Node          { return El("caption").Text(text) }
func Cite(text string) *Node             { return El("cite").Text(text) }
func Code(text string) *Node             { return El("code").Text(text) }
func Col() *Node                         { return El("col") }
func Colgroup(children ...*Node) *Node   { return El("colgroup").Child(children...) }
func Data(text string) *Node             { return El("data").Text(text) }
func Datalist(children ...*Node) *Node   { return El("datalist").Child(children...) }
func Dd(children ...*Node) *Node         { return El("dd").Child(children...) }
func Del(text string) *Node              { return El("del").Text(text) }
func Details(children ...*Node) *Node    { return El("details").Child(children...) }
func Dfn(text string) *Node              { return El("dfn").Text(text) }
func Dialog(children ...*Node) *Node     { return El("dialog").Child(children...) }
func Div(children ...*Node) *Node        { return El("div").Child(children...) }
func Dl(children ...*Node) *Node         { return El("dl").Child(children...) }
func Dt(text string) *Node               { return El("dt").Text(text) }
func Em(text string) *Node               { return El("em").Text(text) }
func Embed() *Node                       { return El("embed") }
func Fieldset(children ...*Node) *Node   { return El("fieldset").Child(children...) }
func Figcaption(children ...*Node) *Node { return El("figcaption").Child(children...) }
func Figure(children ...*Node) *Node     { return El("figure").Child(children...) }
func Footer(children ...*Node) *Node     { return El("footer").Child(children...) }
func Form(children ...*Node) *Node       { return El("form").Child(children...) }
func H1(text string) *Node               { return El("h1").Text(text) }
func H2(text string) *Node               { return El("h2").Text(text) }
func H3(text string) *Node               { return El("h3").Text(text) }
func H4(text string) *Node               { return El("h4").Text(text) }
func H5(text string) *Node               { return El("h5").Text(text) }
func H6(text string) *Node               { return El("h6").Text(text) }
func Head(children ...*Node) *Node       { return El("head").Child(children...) }
func Header(children ...*Node) *Node     { return El("header").Child(children...) }
func Hgroup(children ...*Node) *Node     { return El("hgroup").Child(children...) }
func Hr() *Node                          { return El("hr") }
func Html(children ...*Node) *Node       { return El("html").Child(children...) }
func I(text string) *Node                { return El("i").Text(text) }
func Iframe() *Node                      { return El("iframe") }
func Img() *Node                         { return El("img") }
func Input() *Node                       { return El("input") }
func Ins(text string) *Node              { return El("ins").Text(text) }
func Kbd(text string) *Node              { return El("kbd").Text(text) }
func Label(text string) *Node            { return El("label").Text(text) }
func Legend(text string) *Node           { return El("legend").Text(text) }
func Li(children ...*Node) *Node         { return El("li").Child(children...) }
func Link() *Node                        { return El("link") }
func Main(children ...*Node) *Node       { return El("main").Child(children...) }
func Map(children ...*Node) *Node        { return El("map").Child(children...) }
func Mark(text string) *Node             { return El("mark").Text(text) }
func Menu(children ...*Node) *Node       { return El("menu").Child(children...) }
func Meta() *Node                        { return El("meta") }
func Meter(text string) *Node            { return El("meter").Text(text) }
func Nav(children ...*Node) *Node        { return El("nav").Child(children...) }
func Noscript(children ...*Node) *Node   { return El("noscript").Child(children...) }
func Object(children ...*Node) *Node     { return El("object").Child(children...) }
func Ol(children ...*Node) *Node         { return El("ol").Child(children...) }
func Optgroup(children ...*Node) *Node   { return El("optgroup").Child(children...) }
func Option(text string) *Node           { return El("option").Text(text) }
func Output(text string) *Node           { return El("output").Text(text) }
func P(text string) *Node                { return El("p").Text(text) }
func Picture(children ...*Node) *Node    { return El("picture").Child(children...) }
func Pre(text string) *Node              { return El("pre").Text(text) }
func Progress(text string) *Node         { return El("progress").Text(text) }
func Q(text string) *Node                { return El("q").Text(text) }
func Rp(text string) *Node               { return El("rp").Text(text) }
func Rt(text string) *Node               { return El("rt").Text(text) }
func Ruby(children ...*Node) *Node       { return El("ruby").Child(children...) }
func S(text string) *Node                { return El("s").Text(text) }
func Samp(text string) *Node             { return El("samp").Text(text) }
func Script(text string) *Node           { return El("script").Text(text) }
func Search(children ...*Node) *Node     { return El("search").Child(children...) }
func Section(children ...*Node) *Node    { return El("section").Child(children...) }
func Select(children ...*Node) *Node     { return El("select").Child(children...) }
func Slot(children ...*Node) *Node       { return El("slot").Child(children...) }
func Small(text string) *Node            { return El("small").Text(text) }
func Source() *Node                      { return El("source") }
func Span(text string) *Node             { return El("span").Text(text) }
func Strong(text string) *Node           { return El("strong").Text(text) }
func Sub(text string) *Node              { return El("sub").Text(text) }
func Summary(text string) *Node          { return El("summary").Text(text) }
func Sup(text string) *Node              { return El("sup").Text(text) }
func Table(children ...*Node) *Node      { return El("table").Child(children...) }
func Tbody(children ...*Node) *Node      { return El("tbody").Child(children...) }
func Td(children ...*Node) *Node         { return El("td").Child(children...) }
func Template(children ...*Node) *Node   { return El("template").Child(children...) }
func Textarea(text string) *Node         { return El("textarea").Text(text) }
func Tfoot(children ...*Node) *Node      { return El("tfoot").Child(children...) }
func Th(children ...*Node) *Node         { return El("th").Child(children...) }
func Thead(children ...*Node) *Node      { return El("thead").Child(children...) }
func Time(text string) *Node             { return El("time").Text(text) }
func Title(text string) *Node            { return El("title").Text(text) }
func Tr(children ...*Node) *Node         { return El("tr").Child(children...) }
func Track() *Node                       { return El("track") }
func U(text string) *Node                { return El("u").Text(text) }
func Ul(children ...*Node) *Node         { return El("ul").Child(children...) }
func Var(text string) *Node              { return El("var").Text(text) }
func Video(children ...*Node) *Node      { return El("video").Child(children...) }
func Wbr() *Node                         { return El("wbr") }
