package main

import (
	"fmt"
	"log"
	"os"
	"strings"
)

// tagSpec describes one HTML element: its tag name, and what kind of
// constructor signature makes sense for it.
type tagSpec struct {
	tag  string
	kind string // "children", "text", "void", "custom"
}

// allTags is the full known HTML5 element set. This list is stable —
// HTML rarely adds new elements — so it's hand-maintained here rather
// than fetched, unlike style_generated.go's CSS properties.
var allTags = []tagSpec{
	{"a", "text"}, {"abbr", "text"}, {"address", "children"}, {"area", "void"},
	{"article", "children"}, {"aside", "children"}, {"audio", "children"},
	{"b", "text"}, {"base", "void"}, {"bdi", "text"}, {"bdo", "text"},
	{"blockquote", "children"}, {"body", "children"}, {"br", "void"},
	{"button", "children"}, {"canvas", "children"}, {"caption", "text"},
	{"cite", "text"}, {"code", "text"}, {"col", "void"}, {"colgroup", "children"},
	{"data", "text"}, {"datalist", "children"}, {"dd", "children"}, {"del", "text"},
	{"details", "children"}, {"dfn", "text"}, {"dialog", "children"}, {"div", "children"},
	{"dl", "children"}, {"dt", "text"}, {"em", "text"}, {"embed", "void"},
	{"fieldset", "children"}, {"figcaption", "children"}, {"figure", "children"},
	{"footer", "children"}, {"form", "children"}, {"h1", "text"}, {"h2", "text"},
	{"h3", "text"}, {"h4", "text"}, {"h5", "text"}, {"h6", "text"},
	{"head", "children"}, {"header", "children"}, {"hgroup", "children"},
	{"hr", "void"}, {"html", "children"}, {"i", "text"}, {"iframe", "void"},
	{"img", "void"}, {"input", "void"}, {"ins", "text"}, {"kbd", "text"},
	{"label", "text"}, {"legend", "text"}, {"li", "children"}, {"link", "void"},
	{"main", "children"}, {"map", "children"}, {"mark", "text"}, {"menu", "children"},
	{"meta", "void"}, {"meter", "text"}, {"nav", "children"}, {"noscript", "children"},
	{"object", "children"}, {"ol", "children"}, {"optgroup", "children"},
	{"option", "text"}, {"output", "text"}, {"p", "text"}, {"picture", "children"},
	{"pre", "text"}, {"progress", "text"}, {"q", "text"}, {"rp", "text"},
	{"rt", "text"}, {"ruby", "children"}, {"s", "text"}, {"samp", "text"},
	{"script", "text"}, {"search", "children"}, {"section", "children"},
	{"select", "children"}, {"slot", "children"}, {"small", "text"},
	{"source", "void"}, {"span", "text"}, {"strong", "text"}, {"style", "text"},
	{"sub", "text"}, {"summary", "text"}, {"sup", "text"}, {"table", "children"},
	{"tbody", "children"}, {"td", "children"}, {"template", "children"},
	{"textarea", "text"}, {"tfoot", "children"}, {"th", "children"},
	{"thead", "children"}, {"time", "text"}, {"title", "text"}, {"tr", "children"},
	{"track", "void"}, {"u", "text"}, {"ul", "children"}, {"var", "text"},
	{"video", "children"}, {"wbr", "void"},
}

func main() {
	f, err := os.Create("tags_generated.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by cmd/gentags; DO NOT EDIT.")
	fmt.Fprintln(f, "package htmlbuilder")
	fmt.Fprintln(f)

	for _, t := range allTags {
		if t.tag == "style" {
			continue // custom implementation exists
		}

		name := toPascalCase(t.tag)
		switch t.kind {
		case "void":
			fmt.Fprintf(f, "func %s() *Node { return El(%q) }\n", name, t.tag)
		case "text":
			fmt.Fprintf(f, "func %s(text string) *Node { return El(%q).Text(text) }\n", name, t.tag)
		case "children":
			fmt.Fprintf(f, "func %s(children ...*Node) *Node { return El(%q).Child(children...) }\n", name, t.tag)
		}
	}

	log.Printf("generated %d tag constructors into tags_generated.go\n", len(allTags))
}

func toPascalCase(tag string) string {
	// handles simple tags fine; multi-word tags (colgroup, optgroup) are
	// already single identifiers in HTML, so just capitalize first letter.
	return strings.ToUpper(tag[:1]) + tag[1:]
}
